import type { Account, Transaction, Category, Goal, Bill, Widget, Group, Insight, CashFlowProjection } from './types'

export const mockCategories: Category[] = [
  { id: '1', name: 'Alimentação', icon: 'utensils', color: '#FF6B6B', type: 'expense' },
  { id: '2', name: 'Transporte', icon: 'car', color: '#4ECDC4', type: 'expense' },
  { id: '3', name: 'Moradia', icon: 'home', color: '#45B7D1', type: 'expense' },
  { id: '4', name: 'Lazer', icon: 'gamepad', color: '#96CEB4', type: 'expense' },
  { id: '5', name: 'Saúde', icon: 'heart', color: '#FF8A5B', type: 'expense' },
  { id: '6', name: 'Educação', icon: 'book', color: '#A78BFA', type: 'expense' },
  { id: '7', name: 'Compras', icon: 'shopping-bag', color: '#F472B6', type: 'expense' },
  { id: '8', name: 'Salário', icon: 'briefcase', color: '#34D399', type: 'income' },
  { id: '9', name: 'Freelance', icon: 'laptop', color: '#60A5FA', type: 'income' },
  { id: '10', name: 'Investimentos', icon: 'trending-up', color: '#FBBF24', type: 'income' },
]

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Nubank',
    type: 'checking',
    balance: 12450.00,
    currency: 'BRL',
    color: '#8B5CF6',
    icon: 'credit-card',
    contextId: 'personal',
    contextType: 'personal',
  },
  {
    id: '2',
    name: 'Itaú',
    type: 'checking',
    balance: 8320.50,
    currency: 'BRL',
    color: '#FF6B00',
    icon: 'building',
    contextId: 'personal',
    contextType: 'personal',
  },
  {
    id: '3',
    name: 'XP Investimentos',
    type: 'investment',
    balance: 45000.00,
    currency: 'BRL',
    color: '#00C853',
    icon: 'trending-up',
    contextId: 'personal',
    contextType: 'personal',
  },
  {
    id: '4',
    name: 'Cartão Nubank',
    type: 'credit',
    balance: -2340.00,
    currency: 'BRL',
    color: '#8B5CF6',
    icon: 'credit-card',
    contextId: 'personal',
    contextType: 'personal',
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    accountId: '1',
    amount: -89.90,
    type: 'expense',
    category: mockCategories[0],
    description: 'iFood - Jantar',
    date: new Date('2026-01-18'),
    contextId: 'personal',
    contextType: 'personal',
    createdBy: 'user1',
  },
  {
    id: '2',
    accountId: '1',
    amount: -32.00,
    type: 'expense',
    category: mockCategories[1],
    description: 'Uber - Casa para trabalho',
    date: new Date('2026-01-18'),
    contextId: 'personal',
    contextType: 'personal',
    createdBy: 'user1',
  },
  {
    id: '3',
    accountId: '2',
    amount: 8500.00,
    type: 'income',
    category: mockCategories[7],
    description: 'Salário Janeiro',
    date: new Date('2026-01-05'),
    contextId: 'personal',
    contextType: 'personal',
    createdBy: 'user1',
  },
  {
    id: '4',
    accountId: '1',
    amount: -1200.00,
    type: 'expense',
    category: mockCategories[2],
    description: 'Aluguel Janeiro',
    date: new Date('2026-01-10'),
    contextId: 'personal',
    contextType: 'personal',
    createdBy: 'user1',
  },
  {
    id: '5',
    accountId: '1',
    amount: -156.00,
    type: 'expense',
    category: mockCategories[3],
    description: 'Netflix + Spotify',
    date: new Date('2026-01-15'),
    contextId: 'personal',
    contextType: 'personal',
    createdBy: 'user1',
  },
  {
    id: '6',
    accountId: '4',
    amount: -450.00,
    type: 'expense',
    category: mockCategories[6],
    description: 'Amazon - Eletrônicos',
    date: new Date('2026-01-17'),
    contextId: 'personal',
    contextType: 'personal',
    createdBy: 'user1',
  },
  {
    id: '7',
    accountId: '1',
    amount: 2500.00,
    type: 'income',
    category: mockCategories[8],
    description: 'Projeto Freelance',
    date: new Date('2026-01-12'),
    contextId: 'personal',
    contextType: 'personal',
    createdBy: 'user1',
  },
]

export const mockGoals: Goal[] = [
  {
    id: '1',
    name: 'Viagem Europa',
    targetAmount: 25000,
    currentAmount: 12500,
    deadline: new Date('2026-12-01'),
    icon: 'plane',
    color: '#4ECDC4',
    contextId: 'personal',
    contextType: 'personal',
  },
  {
    id: '2',
    name: 'Reserva de Emergência',
    targetAmount: 30000,
    currentAmount: 22000,
    deadline: new Date('2026-06-01'),
    icon: 'shield',
    color: '#FF6B6B',
    contextId: 'personal',
    contextType: 'personal',
  },
  {
    id: '3',
    name: 'Carro Novo',
    targetAmount: 80000,
    currentAmount: 15000,
    deadline: new Date('2027-06-01'),
    icon: 'car',
    color: '#A78BFA',
    contextId: 'personal',
    contextType: 'personal',
  },
]

export const mockBills: Bill[] = [
  {
    id: '1',
    name: 'Aluguel',
    amount: 1200,
    dueDate: new Date('2026-01-25'),
    recurring: true,
    frequency: 'monthly',
    category: mockCategories[2],
    paid: false,
    contextId: 'personal',
    contextType: 'personal',
  },
  {
    id: '2',
    name: 'Internet',
    amount: 120,
    dueDate: new Date('2026-01-20'),
    recurring: true,
    frequency: 'monthly',
    category: mockCategories[2],
    paid: true,
    contextId: 'personal',
    contextType: 'personal',
  },
  {
    id: '3',
    name: 'Energia',
    amount: 180,
    dueDate: new Date('2026-01-22'),
    recurring: true,
    frequency: 'monthly',
    category: mockCategories[2],
    paid: false,
    contextId: 'personal',
    contextType: 'personal',
  },
]

export const mockWidgets: Widget[] = [
  { id: '1', type: 'balance', position: 0, size: 'large', visible: true },
  { id: '2', type: 'expenses-chart', position: 1, size: 'large', visible: true },
  { id: '3', type: 'recent-transactions', position: 2, size: 'medium', visible: true },
  { id: '4', type: 'goals', position: 3, size: 'medium', visible: true },
  { id: '5', type: 'bills', position: 4, size: 'medium', visible: true },
  { id: '6', type: 'income-expense', position: 5, size: 'medium', visible: true },
]

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Churrasco de Sábado',
    adminId: 'user1',
    members: [
      { id: 'm1', userId: 'user1', name: 'João', role: 'admin', joinedAt: new Date() },
      { id: 'm2', userId: 'user2', name: 'Maria', role: 'member', joinedAt: new Date() },
      { id: 'm3', userId: 'user3', name: 'Pedro', role: 'member', joinedAt: new Date() },
      { id: 'm4', userId: 'user4', name: 'Ana', role: 'member', joinedAt: new Date() },
    ],
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Viagem Carnaval',
    adminId: 'user1',
    members: [
      { id: 'm5', userId: 'user1', name: 'João', role: 'admin', joinedAt: new Date() },
      { id: 'm6', userId: 'user5', name: 'Carlos', role: 'member', joinedAt: new Date() },
      { id: 'm7', userId: 'user6', name: 'Julia', role: 'member', joinedAt: new Date() },
    ],
    createdAt: new Date(),
  },
]

export const mockInsights: Insight[] = [
  {
    id: '1',
    type: 'warning',
    title: 'Conta de luz 20% mais cara',
    description: 'Sua conta de energia deste mês veio R$36 mais cara que a média dos últimos 3 meses.',
    actionLabel: 'Ver detalhes',
    actionUrl: '/bills',
    dismissed: false,
    createdAt: new Date(),
  },
  {
    id: '2',
    type: 'tip',
    title: 'Oportunidade de economia',
    description: 'Você gastou R$890 em alimentação fora. Cozinhando mais, você poderia economizar até R$500/mês.',
    dismissed: false,
    createdAt: new Date(),
  },
  {
    id: '3',
    type: 'achievement',
    title: 'Meta de economia atingida!',
    description: 'Parabéns! Você economizou 15% mais que o mês passado.',
    dismissed: false,
    createdAt: new Date(),
  },
]

export const mockCashFlowProjection: CashFlowProjection[] = [
  { month: 'Jan', income: 11000, expenses: 7500, balance: 3500 },
  { month: 'Fev', income: 11000, expenses: 8200, balance: 2800 },
  { month: 'Mar', income: 13500, expenses: 7800, balance: 5700 },
  { month: 'Abr', income: 11000, expenses: 9000, balance: 2000 },
  { month: 'Mai', income: 11000, expenses: 7200, balance: 3800 },
  { month: 'Jun', income: 14000, expenses: 8500, balance: 5500 },
]

export const mockExpensesByCategory = [
  { name: 'Alimentação', value: 1890, color: '#FF6B6B' },
  { name: 'Transporte', value: 650, color: '#4ECDC4' },
  { name: 'Moradia', value: 1500, color: '#45B7D1' },
  { name: 'Lazer', value: 450, color: '#96CEB4' },
  { name: 'Compras', value: 780, color: '#F472B6' },
  { name: 'Outros', value: 320, color: '#A78BFA' },
]

export const mockGroupDebts = [
  { from: 'Maria', to: 'João', amount: 75 },
  { from: 'Pedro', to: 'João', amount: 45 },
  { from: 'Ana', to: 'Maria', amount: 30 },
]
